### PR TITLE
Updated README for @angular-core/fabric with more info

### PR DESCRIPTION
**Pull request by xjerwa**

### CODE REVIEW

**Comment by bengry** [comment]
@xjerwa looks good, what do you think about adding this also/instead in [the repo's wiki](https://github.com/Microsoft/angular-react/wiki)? There's currently [a page on Fabric](https://github.com/Microsoft/angular-react/wiki/Wrapper-libraries%3A-Fabric) there, but we could expand it into more if needed (e.g. a page per component + one with general notes like the `(click)` vs `(onClick)`).

WDYT?

**Comment by xjerwa** [comment]
@bengry I think that's a good idea. The Wiki actually totally slipped my mind and makes a lot more sense if we want to go more in-depth on each component.

I'm still thinking over how we should approach the more component-specific info. A page for each might be a bit overkill since a majority of the components are simple enough that you could just refer to the official Fabric docs.

**Comment by bengry** [comment]
Agreed, this is why I think of having a general page in the wiki, and then a `README.md` for each file in the repo/wiki, as appropriate - when the component requires it. IIRC you do something similar in your app's repo, no?

**Comment by xjerwa** [comment]
Good point! I think I'll work on finding a good way to get these notes added to the Wiki first. Once we start having more component-specific docs, some sections can start to be removed and linked out to said docs.

**Comment by bengry** [comment]
You can just edit the page in the repo IIRC. Alternatively, use clone the
wiki repo:
https://help.github.com/en/articles/adding-or-editing-wiki-pages#cloning-wikis-to-your-computer

**Pull request closed without merging**
